[package]
name = "blackjack"
version = "0.1.0"
authors = ["Cory Aitchison <corytaitchison@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ndarray = "0.13"